package net.mcreator.fnafmod.block.listener;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.mcreator.fnafmod.init.FnafModModBlockEntities;
import net.mcreator.fnafmod.block.renderer.WhiteClothTableTileRenderer;
import net.mcreator.fnafmod.block.renderer.VassDollTileRenderer;
import net.mcreator.fnafmod.block.renderer.UnWitheredFreddyHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.UnWitheredFoxyHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.UnWitheredChicaHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.UnWitheredBonnieHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.TrashCanTileRenderer;
import net.mcreator.fnafmod.block.renderer.ToyFreddySignOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.ToyFreddySignOffTileRenderer;
import net.mcreator.fnafmod.block.renderer.TortureFreddyTileRenderer;
import net.mcreator.fnafmod.block.renderer.TortureChairTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightRedTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightRedOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightPinkTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightPinkOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightOrangeTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightOrangeOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightGreenTileRenderer;
import net.mcreator.fnafmod.block.renderer.StageLightGreenOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.SpringBonnieHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.SpringBonnieDecorTileRenderer;
import net.mcreator.fnafmod.block.renderer.ShelfTileRenderer;
import net.mcreator.fnafmod.block.renderer.RetroFreddySignTileRenderer;
import net.mcreator.fnafmod.block.renderer.RetroFreddySignOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.RetroComputerTileRenderer;
import net.mcreator.fnafmod.block.renderer.PurpleStripeTableTileRenderer;
import net.mcreator.fnafmod.block.renderer.PurpleStarTableTileRenderer;
import net.mcreator.fnafmod.block.renderer.MeshTrashCanTileRenderer;
import net.mcreator.fnafmod.block.renderer.LargeIndustrialDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.IndustrialFanTileRenderer;
import net.mcreator.fnafmod.block.renderer.GarageDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.FreddysCupcakeBonanzaTileRenderer;
import net.mcreator.fnafmod.block.renderer.FreddySignOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.FreddySignOffTileRenderer;
import net.mcreator.fnafmod.block.renderer.FreddyHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.FredbearSignTileRenderer;
import net.mcreator.fnafmod.block.renderer.FredbearHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.FoxyHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.FoxyHeadDecorationTileRenderer;
import net.mcreator.fnafmod.block.renderer.FluorescentLightTileRenderer;
import net.mcreator.fnafmod.block.renderer.FloodLightsTileRenderer;
import net.mcreator.fnafmod.block.renderer.EndoBlockTileRenderer;
import net.mcreator.fnafmod.block.renderer.DisplayShelvesTileRenderer;
import net.mcreator.fnafmod.block.renderer.ConnectingTableTileRenderer;
import net.mcreator.fnafmod.block.renderer.ClownfulDollTileRenderer;
import net.mcreator.fnafmod.block.renderer.CinematicSignToysTileRenderer;
import net.mcreator.fnafmod.block.renderer.CinematicSignFreddyTileRenderer;
import net.mcreator.fnafmod.block.renderer.CinematicSignBaseTileRenderer;
import net.mcreator.fnafmod.block.renderer.CinematicSignBaseSequelTileRenderer;
import net.mcreator.fnafmod.block.renderer.ChicaHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.ChicaHeadDecorationTileRenderer;
import net.mcreator.fnafmod.block.renderer.CenteredFreddySignTileRenderer;
import net.mcreator.fnafmod.block.renderer.CenteredFreddySignOnTileRenderer;
import net.mcreator.fnafmod.block.renderer.CarouselTileRenderer;
import net.mcreator.fnafmod.block.renderer.BonnieHeadTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigWideRedWindowedDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigWideRedEntranceDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigWideGlassEntranceDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigWideDualColourEntranceDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigWideCyanKitchenDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigWhiteDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigSecurityDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigRedWindowedDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigRedEntranceDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigRedDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigHeavyDutyDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigGlassEntranceDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigDualColourEntranceDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigCyanKitchenDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigCyanBackstageDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigClosetDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BigBackstageDoorTileRenderer;
import net.mcreator.fnafmod.block.renderer.BephDollTileRenderer;
import net.mcreator.fnafmod.block.renderer.AlternateGarageDoorTileRenderer;
import net.mcreator.fnafmod.FnafModMod;

@Mod.EventBusSubscriber(modid = FnafModMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ClientListener {
	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(FnafModModBlockEntities.MESH_TRASH_CAN.get(), context -> new MeshTrashCanTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.TRASH_CAN.get(), context -> new TrashCanTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FREDDY_HEAD.get(), context -> new FreddyHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BONNIE_HEAD.get(), context -> new BonnieHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CHICA_HEAD.get(), context -> new ChicaHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FOXY_HEAD.get(), context -> new FoxyHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FREDBEAR_HEAD.get(), context -> new FredbearHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.SPRING_BONNIE_HEAD.get(), context -> new SpringBonnieHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.ENDO_BLOCK.get(), context -> new EndoBlockTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.UN_WITHERED_FREDDY_HEAD.get(), context -> new UnWitheredFreddyHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.UN_WITHERED_BONNIE_HEAD.get(), context -> new UnWitheredBonnieHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.UN_WITHERED_FOXY_HEAD.get(), context -> new UnWitheredFoxyHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.UN_WITHERED_CHICA_HEAD.get(), context -> new UnWitheredChicaHeadTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.SHELF.get(), context -> new ShelfTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CHICA_HEAD_DECORATION.get(), context -> new ChicaHeadDecorationTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FOXY_HEAD_DECORATION.get(), context -> new FoxyHeadDecorationTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FREDDY_SIGN_OFF.get(), context -> new FreddySignOffTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FREDDY_SIGN_ON.get(), context -> new FreddySignOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.VASS_DOLL.get(), context -> new VassDollTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CENTERED_FREDDY_SIGN.get(), context -> new CenteredFreddySignTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CENTERED_FREDDY_SIGN_ON.get(), context -> new CenteredFreddySignOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BEPH_DOLL.get(), context -> new BephDollTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.TOY_FREDDY_SIGN_OFF.get(), context -> new ToyFreddySignOffTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.TOY_FREDDY_SIGN_ON.get(), context -> new ToyFreddySignOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.RETRO_FREDDY_SIGN.get(), context -> new RetroFreddySignTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.RETRO_FREDDY_SIGN_ON.get(), context -> new RetroFreddySignOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.SPRING_BONNIE_DECOR.get(), context -> new SpringBonnieDecorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FREDBEAR_SIGN.get(), context -> new FredbearSignTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_GREEN.get(), context -> new StageLightGreenTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_PINK.get(), context -> new StageLightPinkTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_ORANGE.get(), context -> new StageLightOrangeTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_RED.get(), context -> new StageLightRedTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_GREEN_ON.get(), context -> new StageLightGreenOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_PINK_ON.get(), context -> new StageLightPinkOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_ORANGE_ON.get(), context -> new StageLightOrangeOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.STAGE_LIGHT_RED_ON.get(), context -> new StageLightRedOnTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.PURPLE_STRIPE_TABLE.get(), context -> new PurpleStripeTableTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.PURPLE_STAR_TABLE.get(), context -> new PurpleStarTableTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.WHITE_CLOTH_TABLE.get(), context -> new WhiteClothTableTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CONNECTING_TABLE.get(), context -> new ConnectingTableTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CAROUSEL.get(), context -> new CarouselTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CLOWNFUL_DOLL.get(), context -> new ClownfulDollTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FREDDYS_CUPCAKE_BONANZA.get(), context -> new FreddysCupcakeBonanzaTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.DISPLAY_SHELVES.get(), context -> new DisplayShelvesTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_BACKSTAGE_DOOR.get(), context -> new BigBackstageDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_CYAN_BACKSTAGE_DOOR.get(), context -> new BigCyanBackstageDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_GLASS_ENTRANCE_DOOR.get(), context -> new BigGlassEntranceDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_RED_ENTRANCE_DOOR.get(), context -> new BigRedEntranceDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_RED_DOOR.get(), context -> new BigRedDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_RED_WINDOWED_DOOR.get(), context -> new BigRedWindowedDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_DUAL_COLOUR_ENTRANCE_DOOR.get(), context -> new BigDualColourEntranceDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_WHITE_DOOR.get(), context -> new BigWhiteDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_CLOSET_DOOR.get(), context -> new BigClosetDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_CYAN_KITCHEN_DOOR.get(), context -> new BigCyanKitchenDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_WIDE_RED_WINDOWED_DOOR.get(), context -> new BigWideRedWindowedDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_WIDE_DUAL_COLOUR_ENTRANCE_DOOR.get(), context -> new BigWideDualColourEntranceDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_WIDE_GLASS_ENTRANCE_DOOR.get(), context -> new BigWideGlassEntranceDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_WIDE_CYAN_KITCHEN_DOOR.get(), context -> new BigWideCyanKitchenDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_WIDE_RED_ENTRANCE_DOOR.get(), context -> new BigWideRedEntranceDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CINEMATIC_SIGN_BASE.get(), context -> new CinematicSignBaseTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CINEMATIC_SIGN_BASE_SEQUEL.get(), context -> new CinematicSignBaseSequelTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CINEMATIC_SIGN_FREDDY.get(), context -> new CinematicSignFreddyTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.CINEMATIC_SIGN_TOYS.get(), context -> new CinematicSignToysTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FLUORESCENT_LIGHT.get(), context -> new FluorescentLightTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.RETRO_COMPUTER.get(), context -> new RetroComputerTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.FLOOD_LIGHTS.get(), context -> new FloodLightsTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_SECURITY_DOOR.get(), context -> new BigSecurityDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.BIG_HEAVY_DUTY_DOOR.get(), context -> new BigHeavyDutyDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.GARAGE_DOOR.get(), context -> new GarageDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.ALTERNATE_GARAGE_DOOR.get(), context -> new AlternateGarageDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.TORTURE_FREDDY.get(), context -> new TortureFreddyTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.TORTURE_CHAIR.get(), context -> new TortureChairTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.LARGE_INDUSTRIAL_DOOR.get(), context -> new LargeIndustrialDoorTileRenderer());
		event.registerBlockEntityRenderer(FnafModModBlockEntities.INDUSTRIAL_FAN.get(), context -> new IndustrialFanTileRenderer());
	}
}
